# (ルート)/Cargo.toml

[workspace]
# このワークスペースに含まれるクレートのパスを指定する
members = [
    "crates/linalg",
    "crates/coding",
    "crates/polynomial",
    "crates/utils",
]

# リリースビルドの最適化設定などをここに集約できる
[profile.release]
lto = true
opt-level = 3