[package]
name = "source-coding"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Source coding algorithms (e.g., arithmetic coding)"

[dependencies]
serde = { version = "1", features = ["derive"] }
thiserror = "1"
