[package]
name = "coding"
version = "0.1.0"
edition = "2021"

[dependencies]
linalg = { path = "../linalg" }
num-traits = "0.2"
serde = { version = "1", features = ["derive" ] }

[dev-dependencies]
pretty_assertions = "1"
