# .devcontainer/docker-compose.yml

version: '3.8'

services:
  # ----------------------------------------
  # Rust / WASM バックエンド用コンテナ
  # ----------------------------------------
  backend:
    # buildセクションで、使用するDockerfileを指定
    build: 
      # ビルドコンテキスト (Dockerfileから見た相対パスの基準) をプロジェクトルートに設定
      context: ..
      # backend用のDockerfileのパス
      dockerfile: .devcontainer/backend/Dockerfile

    # volumesセクションで、ホストPCのディレクトリをコンテナ内にマウント
    volumes:
      # ホストのbackendフォルダを、コンテナ内の/workspaces/backendに同期させる
      - ..:/workspaces/:cached
    working_dir: /workspaces/backend

    # VS Codeがアタッチできるように、コンテナを起動し続けるためのコマンド
    command: sleep infinity
    
    # Rustのデバッガ(LLDB)に必要な設定
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined

  # ----------------------------------------
  # Node.js フロントエンド用コンテナ
  # ----------------------------------------
  frontend:
    build:
      context: ..
      dockerfile: .devcontainer/frontend/Dockerfile

    volumes:
      # ホストのfrontendフォルダを、コンテナ内の/workspaces/frontendに同期させる
      - ..:/workspaces/:cached

    working_dir: /workspaces/frontend

    # portsセクションで、ホストPCとコンテナのポートを繋ぐ
    # これにより、ホストのブラウザから localhost:5173 などでアクセスできる
    ports:
      - 5173:5173 # Viteのデフォルトポート
      - 3000:3000 # create-react-appのデフォルトポート

    command: sleep infinity